### ISSUE TITLE
distributed_vector<std::array<T,N>>, possibly for object of any class stored in DV

### ISSUE THREAD

**Issue by mateuszpn** [oneapi-src/distributed-ranges#103]

**Comment by mateuszpn** [comment]
Shown in stencil-2d.cpp (https://github.com/mateuszpn/distributed-ranges/tree/mhp/stencil-2d, commit 28f316b40ce22420699475966a91f4c697c3afeb) that it works, still with some problems:

1. Direct iteration over DV elements not possible, additional variable necessary 
```c++
	mhp::distributed_vector<Array> a(n, hb);
    for (auto v = a.begin(); v != a.end(); v++) {
      Array _a = *v;  // (*v).begin() fails 
      for (auto e = _a.begin(); e != _a.end(); e++) {
		// ...
      }
	}
```
2. Distributed execution with mpiexec ends with segfault - valgrind shows problem inside halo_impl. Command to see the problem: mpiexec -n 2 ./build/examples/mhp/stencil-2d

**Comment by BenBrock** [comment]
I'm not sure this is going to do what you want, since `Array _a = *v;` is going to copy the whole `std::array` to a local copy.  I think you'd want something more like a vector of remote spans here, so that you're just doing pointer arithmetic when you get a row.  (This is probably orthogonal to your memory problems, though.)
