### ISSUE TITLE
extend inclusive_scan code to support also exclusive_scan

### ISSUE THREAD

**Issue by haichangsi** [oneapi-src/distributed-ranges#546]
do not do it as copy paste

but see how e.g. it is done in oneDPL (there is a template bool parameter)

**Comment by lslusarczyk** [comment]
@haichangsi , The PR is very hard to review because of moving code and changing it in the same PR.

I've created a PR which just moves part of inclusive_scan into new file:
https://github.com/lslusarczyk/distributed-ranges/tree/move_incl_scan_to_separate_header

But when merging this there are conflicts. Could you please resolve them?
That is I am asking you to do on your branch:
```
git remote add lukasz git@github.com:lslusarczyk/distributed-ranges.git
git fetch lukasz
git merge remotes/lukasz/move_incl_scan_to_separate_header
# resolve conflicts
git commit -a
git push # into your exclusive_scan branch inside github
```

If in the meantime my PR https://github.com/oneapi-src/distributed-ranges/pull/549 is approved and merged, then instead of above procedure you will may do simply merge with head and resolve conflicts.
