### ISSUE TITLE
iota (algorithm)

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/distributed-ranges#68]
https://github.com/mateuszpn/distributed-ranges/tree/shp/iota

review, decide if proceed with pull request

**Comment by lslusarczyk** [comment]
@mateuszpn , go ahead with creating PR, but please add tests as well.
I think it does not work now
```
lib::internal::take_segments(lib::ranges::segments(first), last - first);
```
takes too much segments (same as number of elements)

- `sycl::queue()` should take proper device, otherwise it is slow
- `wait` should not be called one-by-one but after issuing all `parallel_for`
- looks like `std::advance(first, (*segment_itr).size());` can jump over `last`
All this should be verified by test.

**Comment by lslusarczyk** [comment]
@haichangsi , please continue work Mateusz has started
First add tests, expose what is not working and fix

**Comment by rscohn2** [comment]
This is iota algorithm implemented with iota view and copy: https://godbolt.org/z/58PxeM5sM
Needs some investigation about whether iota view is random access, permitting parallel decomposition

**Comment by lslusarczyk** [comment]
> Needs some investigation about whether iota view is random access

Even if it is a random access it is not memcpy-able, but this is how our copy works.

I guess generating in place is faster than copying buffers from host to devices - the copy alg would need to be somehow specialized to copy locally on GPU from range created on this GPU into destination without communicating with host at every element. But then this tricky algorithm would work and it would be easy for the user to write plenty of such algorithms.

**Comment by rscohn2** [comment]
Copy should support non-contiguous ranges. It would be implemented with a transform that copies input to output.
