### ISSUE TITLE
take

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/distributed-ranges#93]

**Comment by rscohn2** [comment]
Tests are disabled. For MHP, g++12 build works, but all other compilers fail

**Comment by rscohn2** [comment]
Enabled for SHP, still disabled for MHP

**Comment by lslusarczyk** [comment]
I spend today time trying to narrow problem with disabled mhp tests (disabled [here](https://github.com/oneapi-src/distributed-ranges/blob/main/test/gtest/mhp/mhp-tests.cpp#L38) ). No success yet, but I think I'm getting closer to the place of root cause.

[take segments](https://github.com/oneapi-src/distributed-ranges/blob/main/include/dr/detail/segments_tools.hpp#L38) returns a valid view and _segments_ variable [here](https://github.com/oneapi-src/distributed-ranges/blob/main/test/gtest/include/common-tests.hpp#L127) is a view with rubbish data.

I will continue on Monday.
